# Generated by Django 5.0.3 on 2024-03-25 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Средняя оценка вопроса')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyUserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_index=True, max_length=10, verbose_name='Номер автомобиля')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Средняя оценка')),
                ('published_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Результаты опросов',
                'verbose_name_plural': 'Результаты опросов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyuserresult', verbose_name='Проходивший опрос')),
            ],
            options={
                'verbose_name': 'Оценки пользователей',
                'verbose_name_plural': 'Оценки пользователей',
                'ordering': ['id'],
            },
        ),
    ]
