# Generated by Django 5.0.3 on 2024-03-21 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Номер автомобиля')),
                ('questions_and_ratings', models.JSONField(verbose_name='Вопросы и ответы')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Средняя оценка')),
                ('published_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
            ],
        ),
    ]
