# Generated by Django 5.0.3 on 2024-03-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'ordering': ['id'], 'verbose_name': 'Результаты опросов', 'verbose_name_plural': 'Результаты опросов'},
        ),
        migrations.RenameField(
            model_name='surveyresult',
            old_name='questions_and_ratings',
            new_name='questions_answers',
        ),
    ]
