# Generated by Django 5.0.3 on 2024-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_options_alter_surveyresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Средняя оценка'),
        ),
    ]
