# Generated by Django 5.0.3 on 2024-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_question_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
