# Generated by Django 5.0.3 on 2024-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_question_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Средняя оценка'),
        ),
    ]
