# Generated by Django 5.0.3 on 2024-03-23 17:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_question_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Номер автомобиля')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Средняя оценка')),
                ('published_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Результаты опросов',
                'verbose_name_plural': 'Результаты опросов',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='SurveyResult',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count',
        ),
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyuserresult'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('car_number', 'question')},
        ),
    ]
