# Generated by Django 5.0.3 on 2024-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_survey_surveyuserresult_delete_surveyresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['id'], 'verbose_name': 'Оценки пользователей', 'verbose_name_plural': 'Оценки пользователей'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='question',
            name='question_average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Средняя оценка вопроса'),
        ),
    ]
