# Generated by Django 5.0.3 on 2024-03-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_survey_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='car_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyuserresult', verbose_name='Номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
    ]
